### ISSUE TITLE
Add executable

### ISSUE THREAD

**Issue by kazk** [codewars/cobol-test#3]
In the COBOL image, I'm planning to clone this repo to `/opt/cobol-test` and add `/opt/cobol-test/bin` to `PATH`.

So I can do:
```bash
preprocess-cobol-tests tests.cbl
```
instead of
```bash
python3 /opt/cobol-test/src/preprocessor.py
```

Add shebang:
```python
#!/usr/bin/env python3
```
Move to `bin/preprocess-cobol-tests`, and `chmod +x`.

---

By the way, are there any conventions for the directory with copybooks? Like `include/`?

**Comment by monadius** [comment]
I don't know about any conventions for copybook directories. The ZUT test framework stores all copybooks in `src/main/cobol/copy`. The `src` directory can be renamed to `copy`. But I prefer the `src` name because all COBOL source code is contained in copybooks.

I renamed copybooks to `ddtests.cpy` and `pdtests.cpy` because GnuCOBOL programmer's guide recommends prefixes `dd` for copybooks with data and `pd` for copybooks with code. I also added the `-ffold-case=lower` option to `cobc` to force copybook names to be lower-case (it is important for case sensitive file systems).

**Comment by kazk** [comment]
OK, `src` is fine.

For making an executable, I changed my mind. I think it's better to rename and extend `run`.

`/opt/cobol-test/bin/cw-cobol-test`:
```bash
#!/usr/bin/env bash
set -eu

COBOL_TEST=$(cd $(dirname $0)/../; pwd)

# Preprocess
python3 $COBOL_TEST/src/preprocessor.py ./tests.cbl

# Compile
cobc \
  -x \
  -std=ibm \
  -O2 \
  -fstatic-call \
  -ffold-copy=lower \
  -I $COBOL_TEST/src \
  -I . \
  -o ./tests \
  ./tests-out.cbl \
  ./solution.cbl

# Run
./tests
```

The runner will write files to:

- `/workspace/solution.cbl`
- `/workspace/tests.cbl`
- `/workspace/preloaded.cpy`

Then simply run `cw-cobol-test` in `/workspace`.

**Comment by monadius** [comment]
It is also possible to run the compiled program with the `-j` option of `cobc`.

**Comment by kazk** [comment]
Yeah, confirmed the following to work:
```bash
#!/usr/bin/env bash
set -eu

COBOL_TEST=$(cd $(dirname $0)/../; pwd)

# Preprocess
python3 $COBOL_TEST/src/preprocessor.py ./tests.cbl

# Compile and Run
cobc \
  -x \
  -j \
  -std=ibm \
  -O2 \
  -fstatic-call \
  -ffold-copy=lower \
  -I $COBOL_TEST/src \
  -I . \
  ./tests-out.cbl \
  ./solution.cbl
```

**Comment by monadius** [comment]
I added `bin/cw-cobol-test`. I also made some preprocessor improvements. Please confirm that everything works.

**Comment by kazk** [comment]
Confirmed, thanks.
